export enum typeExpense {
    ALOJAMIENTO = "ALOJAMIENTO",
    DESPL_ESTRUCTURA = "DESPL_ESTRUCTURA",
    DESPL_PUNTUAL = "DESPL_PUNTUAL",
    DESPL_TEMP_TRASLADO = "DESPL_TEMP_TRASLADO",
    GASTOS_ISBAN = "GASTOS_ISBAN",
    LOCOMOCION = "LOCOMOCION",
    TRANSPORTE = "TRANSPORTE",
}