export enum typeExpense {
    ALOJAMIENTO = "Alojamiento",
    DESPL_ESTRUCTURA = "DESPL. ESTRUCTURA",
    DESPL_PUNTUAL = "DESPL. PUNTUAL",
    DESPL_TEMP_TRASLADO = "DESPL. TEMP.TRASLADO",
    GASTOS_ISBAN = "GASTOS ISBAN",
    LOCOMOCION = "Locomocion",
    TRANSPORTE = "Transporte",
}